In [41]:
import numpy as np
import pandas as pd

In [37]:
feature = np.array([[2,3,4,5],[5,6,7,9]])
list_feature = [0,1,3]
k = 3
s = list_feature[0]
print(len(feature))
new_feature = feature[:,s].reshape((len(feature),1))
print(new_feature)
# 获得新的特征数据集
for i in range(1,k):
    s = list_feature[i]
    new_feature = np.hstack((new_feature, feature[:,s].reshape((len(feature),1))))

print(feature)
print(new_feature)

2
[[2]
 [5]]
[[2 3 4 5]
 [5 6 7 9]]
[[2 3 5]
 [5 6 9]]


In [39]:
x = [1,3,4,11,0,3]
x.count(3)

2

In [49]:
acc = 0.5
print("acc = {:.2%}".format(acc))


acc = 50.00%
